import type { ContentCard, Cycle } from './types';

export const MOCK_CYCLE: Cycle = {
  id: 'cycle-012',
  name: 'Cycle 12',
  weekOf: '2026-03-10',
  status: 'active',
  stats: {
    total: 58,
    queue: 2,
    humanReview: 2,
    agentWork: 4,
    published: 14,
    avgCitationScore: 61,
    completionPct: 24,
  },
};

export const PAST_CYCLES: Cycle[] = [
  {
    id: 'cycle-011',
    name: 'Cycle 11',
    weekOf: '2026-03-03',
    status: 'archived',
    stats: { total: 48, queue: 0, humanReview: 0, agentWork: 0, published: 12, avgCitationScore: 67, completionPct: 100 },
  },
  {
    id: 'cycle-010',
    name: 'Cycle 10',
    weekOf: '2026-02-24',
    status: 'archived',
    stats: { total: 42, queue: 0, humanReview: 0, agentWork: 0, published: 10, avgCitationScore: 59, completionPct: 100 },
  },
];

export const INITIAL_CARDS: ContentCard[] = [
  // Queue items
  {
    id: 'IH-009',
    title: 'RBAC Accuracy in AI-Generated Applications',
    type: 'HOW_TO',
    cluster: 'Boundary',
    gap: 0.130,
    score: 85,
    priority: 'P2',
    readTime: 8,
    competitor: 'auth0.com',
    column: 'queue',
    stage: 'queue',
    stageLabel: 'From content planner',
  },
  {
    id: 'IH-010',
    title: 'Webhook Security for AI-Powered Integrations',
    type: 'GUIDE',
    cluster: 'Security',
    gap: 0.165,
    score: 90,
    priority: 'P1',
    readTime: 12,
    competitor: 'snyk.io',
    column: 'queue',
    stage: 'queue',
    stageLabel: 'From content planner',
  },

  // Human review items
  {
    id: 'IH-001',
    title: 'Audit Logs & Change History for AI App Builders',
    type: 'COMPARISON',
    cluster: 'Boundary',
    gap: 0.122,
    score: 87,
    priority: 'P0',
    readTime: 10,
    competitor: 'retool.com',
    column: 'human',
    stage: 'brief_review',
    stageLabel: 'Brief ready for review',
    briefContent: {
      sections: [
        'Introduction to audit logging',
        'Why AI builders need change tracking',
        'Feature comparison matrix',
        'Implementation patterns',
        'Compliance requirements',
        'Best practices',
        'Conclusion',
      ],
      targetWords: 2800,
      exemplarCount: 2,
      sources: [
        { name: 'Retool Audit Guide', domain: 'retool.com', engines: 3 },
        { name: 'Zapier Change Tracking', domain: 'zapier.com', engines: 2 },
      ],
      reasons: [
        'Competitors cited 3.2x more on this cluster — significant gap',
        '1 high-quality exemplar (1,224 words, 11 headers)',
        'How-to format has 86% citation correlation',
      ],
    },
  },
  {
    id: 'IH-002',
    title: 'Pro-Rata Rights Explained: What Every Founder Needs to Know',
    type: 'LONG_BLOG',
    cluster: 'Definition',
    gap: 0.098,
    score: 88,
    priority: 'P0',
    readTime: 14,
    competitor: 'carta.com',
    column: 'human',
    stage: 'article_review',
    stageLabel: 'Article ready for review',
    articleContent: {
      wordCount: 3323,
      targetWords: 3500,
      voiceCompliance: 72,
      sections: [
        { heading: 'What are pro-rata rights?', words: 420, content: 'Pro-rata rights give existing investors the option to participate in future funding rounds to maintain their ownership percentage. Understanding how these rights work — and when to grant them — is critical for founders navigating Series A and beyond.\n\nA pro-rata right (also called a participation right or pre-emptive right) is a contractual provision that allows an investor to invest additional capital in subsequent financing rounds.' },
        { heading: 'How pro-rata calculations work', words: 380, content: 'If an investor owns 10% of a company and the company raises a $5M Series B, the investor\'s pro-rata allocation would be $500,000 (10% × $5M). This allows them to maintain their 10% ownership stake post-dilution.\n\nThe formula: Pro-rata allocation = Current ownership % × New round size.' },
        { heading: 'Standard terms by round', words: 510, content: 'Pro-rata terms evolve across funding stages. At seed, pro-rata rights are rare — most SAFE agreements don\'t include them by default. By Series A, they become standard for lead investors and are typically included in the investors\' rights agreement.' },
        { heading: 'When to grant (and not grant)', words: 440, content: 'Granting pro-rata rights to early investors aligns incentives — investors who can maintain ownership are more motivated to help the company succeed. However, over-committing pro-rata rights can create problems in later rounds.' },
        { heading: 'Pro-rata in your term sheet', words: 390, content: 'In your term sheet, pro-rata rights will typically appear in the investors\' rights agreement rather than the certificate of incorporation.' },
        { heading: 'Pitfalls and negotiation tactics', words: 480, content: 'The most common pitfall is granting broad pro-rata rights to too many small investors at the seed stage. When Series A arrives, you may find that 40% of the round is already spoken for.' },
        { heading: 'Real-world examples', words: 350, content: 'Company A granted rights to all 12 seed investors, consuming 35% of the Series A. Company B limited rights to their lead seed investor only, giving maximum flexibility.' },
        { heading: 'Key takeaways', words: 353, content: 'Limit rights to lead investors at each stage, understand the cumulative impact on future rounds, and always model dilution implications before committing.' },
      ],
      citPrediction: [
        { engine: 'ChatGPT', score: 62 },
        { engine: 'Claude', score: 58 },
        { engine: 'Perplexity', score: 65 },
        { engine: 'Google AI', score: 50 },
        { engine: 'Gemini', score: 55 },
      ],
      compliance: [
        { label: 'Words', current: 3323, target: 3500 },
        { label: 'Headers', current: 11, target: 12 },
        { label: 'Citations', current: 13, target: 15 },
        { label: 'Stats', current: 8, target: 10 },
      ],
      eeat: { overall: 76, experience: 70, expertise: 82, authoritativeness: 78, trustworthiness: 74 },
      interlinks: [
        { title: 'Cap table management guide', path: '/blog/cap-table-management', linked: true },
        { title: 'Equity compensation basics', path: '/blog/equity-compensation-101', linked: false },
        { title: '409A valuation process', path: '/blog/409a-valuations', linked: false },
        { title: 'Series A fundraising checklist', path: '/blog/series-a-checklist', linked: true },
      ],
    },
    metadata: {
      slug: 'pro-rata-rights-explained',
      metaTitle: 'Pro-Rata Rights Explained: What Every Founder Needs to Know',
      metaDescription: 'Learn how pro-rata rights work, when to grant them, and how they affect your cap table. A complete guide for founders navigating Series A and beyond.',
      canonicalUrl: 'https://insighthealth.com/blog/pro-rata-rights-explained',
      schemaMarkup: true,
      publishDate: '2026-03-15',
      author: 'Insight Health Team',
      tags: ['pro-rata rights', 'fundraising', 'term sheets', 'series A'],
    },
  },

  // Agent work items
  {
    id: 'IH-003',
    title: 'International Equity Grants: Tax Compliance Guide',
    type: 'PILLAR_PAGE',
    cluster: 'Mechanism',
    gap: 0.175,
    score: 93,
    priority: 'P0',
    readTime: 15,
    competitor: 'deel.com',
    column: 'agent',
    stage: 'writing',
    stageLabel: 'Writing — section 4 of 7',
    agentProgress: {
      pct: 34,
      currentTask: 'Writing section 4: Tax Implications by Jurisdiction',
      wordsCurrent: 1194,
      wordsTarget: 3500,
      sectionsComplete: 3,
      sectionsTotal: 7,
    },
  },
  {
    id: 'IH-004',
    title: 'Secrets & Environment Variables in Prompt-to-App Tools',
    type: 'HOW_TO',
    cluster: 'Mechanism',
    gap: 0.175,
    score: 91,
    priority: 'P1',
    readTime: 8,
    competitor: 'netlify.com',
    column: 'agent',
    stage: 'brief_generation',
    stageLabel: 'Generating brief',
    agentProgress: {
      pct: 60,
      currentTask: 'Analyzing exemplar structure',
    },
  },
  {
    id: 'IH-005',
    title: 'SOC 2 + GDPR for AI Development Platforms',
    type: 'GUIDE',
    cluster: 'Boundary',
    gap: 0.159,
    score: 89,
    priority: 'P2',
    readTime: 12,
    competitor: 'vanta.com',
    column: 'agent',
    stage: 'planning',
    stageLabel: 'Planning — analyzing queries',
    agentProgress: {
      pct: 20,
      currentTask: 'Analyzing 200 query scorecards',
    },
  },
  {
    id: 'IH-006',
    title: 'Bolt.new Alternatives 2026: Complete Comparison',
    type: 'COMPARISON',
    cluster: 'Category',
    gap: 0.141,
    score: 92,
    priority: 'P1',
    readTime: 10,
    competitor: 'g2.com',
    column: 'agent',
    stage: 'evaluating',
    stageLabel: 'Evaluating — cycle 1',
    agentProgress: {
      pct: 85,
      currentTask: 'Eval: structural 0.82, semantic 0.78, style 0.85',
    },
  },
];

// Generate mock brief content when agent completes planning/brief_generation
export function generateMockBrief(): ContentCard['briefContent'] {
  return {
    sections: [
      'Introduction and overview',
      'Key concepts explained',
      'Implementation guide',
      'Best practices',
      'Common pitfalls',
      'Case studies',
      'Conclusion and next steps',
    ],
    targetWords: 3000,
    exemplarCount: 3,
    sources: [
      { name: 'Industry Guide', domain: 'example.com', engines: 3 },
      { name: 'Best Practices Report', domain: 'docs.example.com', engines: 2 },
    ],
    reasons: [
      'High gap score indicates significant content opportunity',
      'Multiple exemplars with strong citation correlation',
      'Topic trending in AI engine responses',
    ],
  };
}

// Generate mock article content when agent completes writing/evaluating
export function generateMockArticle(): ContentCard['articleContent'] {
  return {
    wordCount: 2800,
    targetWords: 3000,
    voiceCompliance: 78,
    sections: [
      { heading: 'Introduction', words: 350, content: 'This comprehensive guide explores the key concepts and practical implementation strategies that organizations need to understand in today\'s rapidly evolving landscape.' },
      { heading: 'Core concepts', words: 420, content: 'Understanding the foundational principles is critical before diving into implementation. These concepts form the basis for all subsequent decisions and strategies.' },
      { heading: 'Implementation guide', words: 500, content: 'Step-by-step instructions for implementing the described approach, including code examples, configuration details, and integration points with existing systems.' },
      { heading: 'Best practices', words: 380, content: 'Industry-proven approaches that maximize effectiveness while minimizing risk. Each practice is backed by real-world data and case studies.' },
      { heading: 'Common pitfalls', words: 350, content: 'Common mistakes to avoid, drawn from analysis of hundreds of implementations. Understanding these pitfalls saves significant time and resources.' },
      { heading: 'Case studies', words: 450, content: 'Real-world examples demonstrating successful implementations, including metrics, timelines, and lessons learned from each organization.' },
      { heading: 'Key takeaways', words: 350, content: 'Summary of the most important points, with actionable next steps for immediate implementation.' },
    ],
    citPrediction: [
      { engine: 'ChatGPT', score: 58 },
      { engine: 'Claude', score: 62 },
      { engine: 'Perplexity', score: 55 },
      { engine: 'Google AI', score: 48 },
      { engine: 'Gemini', score: 52 },
    ],
    compliance: [
      { label: 'Words', current: 2800, target: 3000 },
      { label: 'Headers', current: 9, target: 10 },
      { label: 'Citations', current: 11, target: 14 },
      { label: 'Stats', current: 6, target: 8 },
    ],
    eeat: { overall: 72, experience: 68, expertise: 78, authoritativeness: 74, trustworthiness: 70 },
    interlinks: [
      { title: 'Getting started guide', path: '/blog/getting-started', linked: true },
      { title: 'Advanced configuration', path: '/blog/advanced-config', linked: false },
      { title: 'API reference', path: '/docs/api', linked: false },
    ],
  };
}
