"""Create daily tracker tables — tracked_prompts, daily_runs, daily_run_responses.

Hand-written migration (not autogenerated) following the project convention.
Uses plain VARCHAR for status/source columns (not PG enums) to avoid
migration friction when new values are added.

Revision ID: 0005
Revises: 0004
Create Date: 2026-02-28
"""
from __future__ import annotations

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects.postgresql import JSONB, UUID as PgUUID

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str = "0004"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ── tracked_prompts ────────────────────────────────────────────────
    op.create_table(
        "tracked_prompts",
        sa.Column(
            "id",
            PgUUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("company_id", sa.String, nullable=False),
        sa.Column("text", sa.Text, nullable=False),
        sa.Column("category", sa.String, nullable=True),
        sa.Column("tags", JSONB, nullable=False, server_default="[]"),
        sa.Column("source", sa.String, nullable=False, server_default="manual"),
        sa.Column("source_metadata", JSONB, nullable=True),
        sa.Column("active", sa.Boolean, nullable=False, server_default="true"),
        sa.Column("platforms", JSONB, nullable=False, server_default="[]"),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index(
        "ix_tracked_prompts_company_id", "tracked_prompts", ["company_id"]
    )
    op.create_index(
        "ix_tracked_prompts_company_active",
        "tracked_prompts",
        ["company_id", "active"],
    )
    op.create_index(
        "ix_tracked_prompts_source", "tracked_prompts", ["source"]
    )

    # ── daily_runs ─────────────────────────────────────────────────────
    op.create_table(
        "daily_runs",
        sa.Column(
            "id",
            PgUUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column("company_id", sa.String, nullable=False),
        sa.Column("status", sa.String, nullable=False, server_default="pending"),
        sa.Column("config", JSONB, nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("error", sa.Text, nullable=True),
        sa.Column(
            "prompt_count", sa.Integer, nullable=False, server_default="0"
        ),
        sa.Column(
            "engine_count", sa.Integer, nullable=False, server_default="0"
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index("ix_daily_runs_company_id", "daily_runs", ["company_id"])
    op.create_index("ix_daily_runs_status", "daily_runs", ["status"])
    op.create_index(
        "ix_daily_runs_company_status", "daily_runs", ["company_id", "status"]
    )

    # ── daily_run_responses ────────────────────────────────────────────
    op.create_table(
        "daily_run_responses",
        sa.Column(
            "id",
            PgUUID(as_uuid=True),
            primary_key=True,
            server_default=sa.text("gen_random_uuid()"),
        ),
        sa.Column(
            "run_id",
            PgUUID(as_uuid=True),
            sa.ForeignKey("daily_runs.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column(
            "prompt_id",
            PgUUID(as_uuid=True),
            sa.ForeignKey("tracked_prompts.id", ondelete="CASCADE"),
            nullable=False,
        ),
        sa.Column("engine", sa.String, nullable=False),
        sa.Column("response_text", sa.Text, nullable=False, server_default=""),
        sa.Column("latency_ms", sa.Float, nullable=False, server_default="0"),
        sa.Column("error", sa.Text, nullable=True),
        sa.Column(
            "brand_mentioned",
            sa.Boolean,
            nullable=False,
            server_default="false",
        ),
        sa.Column(
            "brand_mention_count",
            sa.Integer,
            nullable=False,
            server_default="0",
        ),
        sa.Column(
            "competitor_mentions", JSONB, nullable=False, server_default="{}"
        ),
        sa.Column("citations", JSONB, nullable=False, server_default="[]"),
        sa.Column("citation_rank", sa.Integer, nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            nullable=False,
            server_default=sa.func.now(),
        ),
    )
    op.create_index(
        "ix_daily_run_responses_run_id", "daily_run_responses", ["run_id"]
    )
    op.create_index(
        "ix_daily_run_responses_prompt_id",
        "daily_run_responses",
        ["prompt_id"],
    )
    op.create_index(
        "ix_daily_run_responses_run_engine",
        "daily_run_responses",
        ["run_id", "engine"],
    )


def downgrade() -> None:
    # Drop in reverse order to respect FK constraints.
    op.drop_index(
        "ix_daily_run_responses_run_engine", table_name="daily_run_responses"
    )
    op.drop_index(
        "ix_daily_run_responses_prompt_id", table_name="daily_run_responses"
    )
    op.drop_index(
        "ix_daily_run_responses_run_id", table_name="daily_run_responses"
    )
    op.drop_table("daily_run_responses")

    op.drop_index("ix_daily_runs_company_status", table_name="daily_runs")
    op.drop_index("ix_daily_runs_status", table_name="daily_runs")
    op.drop_index("ix_daily_runs_company_id", table_name="daily_runs")
    op.drop_table("daily_runs")

    op.drop_index(
        "ix_tracked_prompts_source", table_name="tracked_prompts"
    )
    op.drop_index(
        "ix_tracked_prompts_company_active", table_name="tracked_prompts"
    )
    op.drop_index(
        "ix_tracked_prompts_company_id", table_name="tracked_prompts"
    )
    op.drop_table("tracked_prompts")
